FROM openjdk:11

EXPOSE 8097

RUN apt-get update && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/* \
    && git clone https://github.com/SexualWhiteChocolate/ISD_BIT_Lab2.git \
    && rm -rf /ISD_BIT_Lab2/task1 ISD_BIT_Lab2/task2/Producer docker* Docker* init.sh my.cnf mysqlscript.sql

WORKDIR /ISD_BIT_Lab2/task2/Consumer

RUN javac Main.java \
    && rm -rf ru && rm -rf Main.* MiniClass.*

WORKDIR /ISD_BIT_Lab2/task2

CMD [""]