version: "3.7"

services:
  mysql:
    container_name: mysql
    image: karimullin_mysql
#    command: mysqld --init-file="/docker-entrypoint-initdb.d/schema.sql"
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - karimullin_db_data_volume:/root
    networks:
      karimullin_network:
        ipv4_address: 172.18.0.4
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 30s
      timeout: 10s
      retries: 5

  consumer:
    container_name: consumer
    image: karimullin_consumer
    command: nohup java -cp /ISD_BIT_Lab2/task2/Consumer:/ISD_BIT_Lab2/task2/Consumer/mysql-connector-java-8.0.30.jar Main &
    restart: unless-stopped
    networks:
      karimullin_network:
        ipv4_address: 172.18.0.2
    depends_on:
      mysql:
        condition: service_healthy

  producer:
    container_name: producer
    image: karimullin_producer
    command: nohup java -jar Producer.jar &
    restart: unless-stopped
    networks:
      karimullin_network:
        ipv4_address: 172.18.0.3
    depends_on:
      - consumer

networks:
  karimullin_network:
    driver: bridge
    name: karimullin_network
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  karimullin_db_data_volume:
    name: karimullin_db_data_volume
    driver: local