FROM openjdk:11

EXPOSE 8097

RUN apt-get update && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/* \
    && git clone https://github.com/SexualWhiteChocolate/ISD_BIT_Lab2.git \
    && rm -rf /ISD_BIT_Lab2/task1 ISD_BIT_Lab2/task2/Consumer docker* Docker* init.sh

WORKDIR /ISD_BIT_Lab2/task2/Producer

RUN javac Main.java \
    && jar cfe Producer.jar Main Main.class MiniClass.class \
    && rm -rf Main.* MiniClass.*

CMD [""]