--CREATE DATABASE IF NOT EXISTS '';
--USE mydatabase;
CREATE TABLE IF NOT EXISTS mytable (timestamp VARCHAR(255) PRIMARY KEY, jsoned_object VARCHAR(1023));
CREATE USER 'user'@'172.18.0.2' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON mydatabase.* TO 'user'@'172.18.0.2' WITH GRANT OPTION;
